# Generated by Django 5.2.5 on 2025-08-26 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ATName', models.CharField(max_length=50, unique=True, verbose_name='Author name')),
                ('ATDesc', models.TextField(blank=True, null=True, verbose_name='Author description')),
                ('ATImg', models.ImageField(blank=True, null=True, upload_to='book/', verbose_name='author image')),
                ('ATOrigin', models.CharField(blank=True, max_length=50, null=True, verbose_name='Origin')),
                ('ATLanguage', models.CharField(choices=[('Not available', 'Not available'), ('Anglais', 'Anglais'), ('Français', 'Français'), ('Arabe', 'Arabe'), ('Italien', 'Italien'), ('Espagnole', 'Espagnole'), ('Allemand', 'Allemand')], default='Arabe', max_length=20)),
                ('ATSlug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USName', models.CharField(max_length=100, verbose_name='username')),
                ('USEmail', models.EmailField(max_length=254, verbose_name='accessories')),
                ('USImage', models.ImageField(blank=True, null=True, upload_to='book/', verbose_name='user image')),
                ('USPassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATName', models.CharField(max_length=50, verbose_name='category name')),
                ('CATDesc', models.TextField(verbose_name='category description')),
                ('CATImg', models.ImageField(upload_to='book/', verbose_name='category image')),
                ('CATParent', models.ForeignKey(blank=True, limit_choices_to={'CATParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.category', verbose_name='Main category')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BKTitle', models.CharField(max_length=100, verbose_name='book title')),
                ('BKLanguage', models.CharField(choices=[('Not available', 'Not available'), ('Anglais', 'Anglais'), ('Français', 'Français'), ('Arabe', 'Arabe'), ('Italien', 'Italien'), ('Espagnole', 'Espagnole'), ('Allemand', 'Allemand')], default='Not available', max_length=20)),
                ('BKDescription', models.TextField(verbose_name='book description')),
                ('BKImage', models.ImageField(blank=True, null=True, upload_to='book/', verbose_name='image')),
                ('BKFile', models.FileField(blank=True, null=True, upload_to='book/')),
                ('BKSlug', models.SlugField(blank=True, null=True)),
                ('BKAuthor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.author')),
                ('BKCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.category')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial', to='books.user')),
            ],
        ),
    ]
